theme: minima
title: Adrian Panek's blog
author: Adrian Panek
description: Welcome to my blog. I'm Adrian, DevOps Engineer currently employed in UBS. Main purpose of my blog is to share my knowledge about Software Enginnering as well as productivity and self-development. Stay tuned for my posts!